#!/bin/bash

#PBS -P personal-e1583377
#PBS -j oe
#PBS -N pytorch

#PBS -q interactive_gpu
#PBS -l select=1:ncpus=1:ngpus=1:mem=32GB
#PBS -l walltime=12:00:00
cd $PBS_O_WORKDIR;
image="/app1/common/singularity-img/hopper/cuda/cuda_12.1.1-cudnn8-devel-ubuntu22.04.sif"
module load singularity
singularity exec -e $image bash << EOF > stdout.$PBS_JOBID 2> stderr.$PBS_JOBID
export PYTHONPATH=$PYTHONPATH:/home/svu/e1583377/hopper_pypkg/cuda/cuda_12.1.1-cudnn8-devel-ubuntu22.04/local/lib/python3.10/dist-packages
# Run your scripts
cd scripts
#python3.10 early_fusion_classifier_inference.py > stdout.$PBS_JOBID 2> stderr.$PBS_JOBID
python3.10 constrained_early_fusion_inference.py > stdout.$PBS_JOBID 2> stderr.$PBS_JOBID
#python3.10 compute_auroc_and_cmap.py > stdout.$PBS_JOBID 2> stderr.$PBS_JOBID