#!/bin/bash

#PBS -P personal-e1583377
#PBS -j oe
#PBS -N pytorch

#PBS -q auto_free
#PBS -l select=1:ncpus=1:ngpus=1:mem=240GB
#PBS -l walltime=24:00:00
cd $PBS_O_WORKDIR;
image="/app1/common/singularity-img/hopper/cuda/cuda_12.1.0-cudnn8-devel-u20.04.sif"
module load singularity
export LD_LIBRARY_PATH=/host-driver-libs:/usr/lib/x86_64-linux-gnu:/usr/local/cuda-12.1/lib64:$LD_LIBRARY_PATH
singularity exec -e --nv \
  --bind $(ldconfig -p | grep libcuda.so.1 | awk '{print $NF}'):/host-libcuda.so.1 \
  --env PBS_JOBID=$PBS_JOBID \
  $image bash <<'EOF'
export LD_LIBRARY_PATH=/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/.singularity.d/libs:$(dirname /host-libcuda.so.1):$LD_LIBRARY_PATH
python3.10 -c "import ctypes, sys; ctypes.CDLL('/host-libcuda.so.1'); print('libcuda OK')"
python3.10 -c "import tensorflow as tf; print('TF GPUs:', tf.config.list_physical_devices('GPU'))"
export LD_LIBRARY_PATH=$HOME/.local/lib/python3.10/site-packages/nvidia/cudnn/lib:$LD_LIBRARY_PATH
export PYTHONPATH=$PYTHONPATH:/home/svu/e1583377/hopper_pypkg/cuda/cuda_12.1.0-cudnn8-devel-u20.04/local/lib/python3.10/dist-packages
export PATH=$HOME/bin:$PATH
export CUDA_VISIBLE_DEVICES="0"
#export LD_LIBRARY_PATH="/cm/local/apps/cuda/libs/current/lib64:/home/svu/e1583377/.local/lib/python3.10/site-packages/nvidia/cudnn/lib:$LD_LIBRARY_PATH"
# Run your scripts
cd scripts
#python3.10 compute_inat_embeddings.py > stdout.$PBS_JOBID 2> stderr.$PBS_JOBID
python3.10 compute_mixup_inat_embeddings.py > stdout.$PBS_JOBID 2> stderr.$PBS_JOBID
